import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import { config } from 'dotenv'

config()

const FILE_ID = process.env.FIGMA_FILE_ID
const TOKEN = process.env.FIGMA_TOKEN
const OUTPUT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), 'src/tokens.css')

if (!FILE_ID || !TOKEN) {
  console.error('Missing FIGMA_FILE_ID or FIGMA_TOKEN in .env')
  process.exit(1)
}

async function fetchVariables() {
  const res = await fetch(`https://api.figma.com/v1/files/${FILE_ID}/variables/local`, {
    headers: { 'X-Figma-Token': TOKEN },
  })
  if (!res.ok) throw new Error(`Figma API error: ${res.status} ${res.statusText}`)
  return res.json()
}

function figmaColorToOklch(color) {
  // Figma returns RGBA 0-1 floats — convert to hex for now
  const r = Math.round(color.r * 255).toString(16).padStart(2, '0')
  const g = Math.round(color.g * 255).toString(16).padStart(2, '0')
  const b = Math.round(color.b * 255).toString(16).padStart(2, '0')
  return `#${r}${g}${b}`
}

function resolveValue(variable, variables, modeId) {
  const value = variable.valuesByMode[modeId]
  if (!value) return null

  // Alias — resolve to the referenced variable
  if (value.type === 'VARIABLE_ALIAS') {
    const referenced = variables[value.id]
    if (!referenced) return null
    // Use the same mode if available, otherwise first mode
    const refModeId = referenced.valuesByMode[modeId] ? modeId : Object.keys(referenced.valuesByMode)[0]
    return resolveValue(referenced, variables, refModeId)
  }

  // Color value
  if (value.r !== undefined) return figmaColorToOklch(value)

  // Number value
  if (typeof value === 'number') return `${value}px`

  return null
}

async function main() {
  console.log('Fetching variables from Figma...')
  const data = await fetchVariables()

  const { variableCollections, variables } = data.meta

  // Find Tokens collection
  const tokensCollection = Object.values(variableCollections).find(c => c.name === 'Tokens')
  const primitivesCollection = Object.values(variableCollections).find(c => c.name === 'Primitives')
  const radiusCollection = Object.values(variableCollections).find(c => c.name === 'Radius')

  if (!tokensCollection) {
    console.error('Could not find Tokens collection in Figma file')
    process.exit(1)
  }

  // Get Light and Dark mode IDs
  const lightMode = tokensCollection.modes.find(m => m.name === 'Light')
  const darkMode = tokensCollection.modes.find(m => m.name === 'Dark')

  if (!lightMode || !darkMode) {
    console.error('Could not find Light/Dark modes in Tokens collection')
    process.exit(1)
  }

  // Build variable maps
  const variableMap = Object.fromEntries(
    Object.values(variables).map(v => [v.id, v])
  )

  // Get token variables
  const tokenVars = Object.values(variables).filter(
    v => v.variableCollectionId === tokensCollection.id
  )

  // Get primitive variables
  const primitiveVars = primitivesCollection
    ? Object.values(variables).filter(v => v.variableCollectionId === primitivesCollection.id)
    : []

  // Get radius variables
  const radiusVars = radiusCollection
    ? Object.values(variables).filter(v => v.variableCollectionId === radiusCollection.id)
    : []

  // Build CSS
  const lines = []

  // Primitives (brand colors)
  if (primitiveVars.length) {
    lines.push('/* Primitives */')
    for (const v of primitiveVars) {
      const modeId = Object.keys(v.valuesByMode)[0]
      const value = resolveValue(v, variableMap, modeId)
      if (value) lines.push(`  --brand-${v.name.replace('brand/', '')}: ${value};`)
    }
    lines.push('')
  }

  // Semantic tokens — Light mode
  lines.push('/* Semantic Tokens — Light */')
  for (const v of tokenVars) {
    const value = resolveValue(v, variableMap, lightMode.id)
    const name = v.name.replace('color/', 'color-')
    if (value) lines.push(`  --${name}: ${value};`)
  }

  // Radius
  if (radiusVars.length) {
    lines.push('')
    lines.push('/* Radius */')
    for (const v of radiusVars) {
      const modeId = Object.keys(v.valuesByMode)[0]
      const value = resolveValue(v, variableMap, modeId)
      if (value) lines.push(`  --radius-${v.name}: ${value};`)
    }
  }

  const lightBlock = `:root {\n${lines.join('\n')}\n}`

  // Dark mode tokens
  const darkLines = []
  darkLines.push('/* Semantic Tokens — Dark */')
  for (const v of tokenVars) {
    const value = resolveValue(v, variableMap, darkMode.id)
    const name = v.name.replace('color/', 'color-')
    if (value) darkLines.push(`  --${name}: ${value};`)
  }

  const darkBlock = `.dark {\n${darkLines.join('\n')}\n}`

  const output = `/* Auto-generated by sync-tokens.mjs — do not edit manually */\n/* Run: node sync-tokens.mjs to regenerate */\n\n${lightBlock}\n\n${darkBlock}\n`

  fs.writeFileSync(OUTPUT, output, 'utf8')
  console.log(`✓ Tokens written to ${OUTPUT}`)
}

main().catch(err => {
  console.error('Error:', err.message)
  process.exit(1)
})
